[package]
name = "wasm-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
sycamore = "0.8"
wasm-bindgen = "=0.2.93"
web-sys = { version = "0.3", features = ["Window", "Document", "Element"] }

[lib]
crate-type = ["cdylib"]